"""
constants.py — Constantes globales: fases, banderas, jugadores, categorías especiales.
"""

FASES = ["Grupos", "Dieciseisavos", "Octavos", "Cuartos", "Semifinal", "Final"]

CATEGORIAS_ESPECIALES = {
    "campeon":  {"label": "🏆 Campeón del Mundial",  "puntos": 20},
    "goleador": {"label": "⚽ Goleador del Mundial",  "puntos": 10},
    "arquero":  {"label": "🧤 Mejor Arquero",         "puntos": 8},
    "jugador":  {"label": "⭐ Mejor Jugador (MVP)",   "puntos": 8},
}

BANDERAS = {
    "Argentina": "🇦🇷", "Brasil": "🇧🇷", "Uruguay": "🇺🇾", "Colombia": "🇨🇴",
    "Ecuador": "🇪🇨", "Paraguay": "🇵🇾", "Chile": "🇨🇱", "Venezuela": "🇻🇪",
    "Peru": "🇵🇪", "Bolivia": "🇧🇴",
    "EEUU": "🇺🇸", "Canada": "🇨🇦", "Mexico": "🇲🇽", "Haiti": "🇭🇹",
    "Jamaica": "🇯🇲", "Panama": "🇵🇦", "Costa Rica": "🇨🇷", "Honduras": "🇭🇳",
    "El Salvador": "🇸🇻", "Curazao": "🇨🇼", "Trinidad y Tobago": "🇹🇹",
    "Francia": "🇫🇷", "Alemania": "🇩🇪", "España": "🇪🇸", "Inglaterra": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "Portugal": "🇵🇹", "Paises Bajos": "🇳🇱", "Belgica": "🇧🇪", "Italia": "🇮🇹",
    "Croacia": "🇭🇷", "Suiza": "🇨🇭", "Austria": "🇦🇹", "Dinamarca": "🇩🇰",
    "Suecia": "🇸🇪", "Noruega": "🇳🇴", "Polonia": "🇵🇱", "Ucrania": "🇺🇦",
    "Turquia": "🇹🇷", "Escocia": "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "Gales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿", "Irlanda": "🇮🇪",
    "Grecia": "🇬🇷", "Hungria": "🇭🇺", "Serbia": "🇷🇸", "Eslovenia": "🇸🇮",
    "Rumania": "🇷🇴", "Eslovaquia": "🇸🇰", "Albania": "🇦🇱", "Georgia": "🇬🇪",
    "Republica Checa": "🇨🇿",
    "Marruecos": "🇲🇦", "Senegal": "🇸🇳", "Ghana": "🇬🇭", "Nigeria": "🇳🇬",
    "Costa de Marfil": "🇨🇮", "Egipto": "🇪🇬", "Tunez": "🇹🇳", "Argelia": "🇩🇿",
    "Cabo Verde": "🇨🇻", "Sudafrica": "🇿🇦", "Camerun": "🇨🇲", "Mali": "🇲🇱",
    "Guinea": "🇬🇳", "Tanzania": "🇹🇿", "Congo": "🇨🇬",
    "Japon": "🇯🇵", "Corea del Sur": "🇰🇷", "Australia": "🇦🇺", "Iran": "🇮🇷",
    "Arabia Saudita": "🇸🇦", "Catar": "🇶🇦", "Uzbekistan": "🇺🇿", "Jordania": "🇯🇴",
    "Irak": "🇮🇶", "Emiratos": "🇦🇪", "Nueva Zelanda": "🇳🇿", "Fiji": "🇫🇯",
    "Indonesia": "🇮🇩", "China": "🇨🇳", "India": "🇮🇳",
}

JUGADORES_MUNDIALISTAS = sorted([
    "Lionel Messi", "Ángel Di María", "Lautaro Martínez", "Julián Álvarez",
    "Rodrigo De Paul", "Alexis Mac Allister", "Cristian Romero", "Nicolás Otamendi",
    "Neymar Jr", "Vinicius Jr", "Rodrygo", "Raphinha", "Bruno Guimarães",
    "Kylian Mbappé", "Antoine Griezmann", "Ousmane Dembélé", "Aurélien Tchouaméni",
    "Erling Haaland", "Martin Ødegaard", "Alexander Isak",
    "Harry Kane", "Jude Bellingham", "Phil Foden", "Bukayo Saka", "Marcus Rashford",
    "Cristiano Ronaldo", "Bruno Fernandes", "Bernardo Silva", "Rúben Dias",
    "Pedri", "Lamine Yamal", "Álvaro Morata", "Rodri", "Gavi",
    "Leroy Sané", "Florian Wirtz", "Jamal Musiala", "Kai Havertz", "Thomas Müller",
    "Romelu Lukaku", "Kevin De Bruyne", "Dodi Lukebakio",
    "Ciro Immobile", "Federico Chiesa", "Nicolo Barella",
    "Memphis Depay", "Xavi Simons", "Cody Gakpo",
    "Luka Modric", "Ivan Perisic", "Mateo Kovacic",
    "Granit Xhaka", "Xherdan Shaqiri", "Breel Embolo",
    "Robert Lewandowski", "Piotr Zielinski",
    "Mohamed Salah", "Mostafa Mohamed",
    "Sadio Mané", "Ismaïla Sarr",
    "Riyad Mahrez", "Islam Slimani",
    "Hakim Ziyech", "Youssef En-Nesyri", "Achraf Hakimi",
    "Victor Osimhen", "Kelechi Iheanacho",
    "André Ayew", "Jordan Ayew",
    "Sébastien Haller", "Franck Kessié",
    "Hiroki Sakai", "Takumi Minamino", "Daichi Kamada",
    "Son Heung-min", "Hwang Hee-chan",
    "Mathew Leckie", "Martin Boyle",
    "Christian Pulisic", "Weston McKennie", "Tyler Adams", "Tim Weah",
    "Alphonso Davies", "Jonathan David", "Cyle Larin",
    "Hirving Lozano", "Raúl Jiménez", "Henry Martín",
    "Luis Díaz", "James Rodríguez", "Falcao",
    "Enner Valencia", "Moisés Caicedo",
    "Darwin Núñez", "Federico Valverde", "Luis Suárez",
    "Miguel Almirón", "Ángel Romero",
    "Gianluca Lapadula", "André Carrillo",
    "Jhon Durán", "Rafael Santos Borré",
    "Dusan Vlahovic", "Sergej Milinkovic-Savic",
    "Khvicha Kvaratskhelia", "Georges Mikautadze",
    "Giorgi Mamardashvili",
    "Cengiz Ünder", "Hakan Çalhanoğlu", "Arda Güler",
    "Victor Boniface", "Ademola Lookman",
    "Emre Can", "İlkay Gündoğan",
    "Marco Asensio", "Dani Olmo",
    "Ansu Fati", "Ferran Torres",
])

ARQUEROS_MUNDIALISTAS = sorted([
    "Emiliano Martínez", "Franco Armani",
    "Alisson Becker", "Ederson", "Weverton",
    "Hugo Lloris", "Mike Maignan", "Alphonse Areola",
    "Thibaut Courtois", "Koen Casteels", "Simon Mignolet",
    "Manuel Neuer", "Marc-André ter Stegen", "Kevin Trapp",
    "David de Gea", "Unai Simón", "Robert Sánchez",
    "Gianluigi Donnarumma", "Alex Meret",
    "Jordan Pickford", "Nick Pope", "Aaron Ramsdale",
    "Rui Patrício", "Diogo Costa",
    "Yassine Bounou", "Munir",
    "Édouard Mendy", "Seny Dieng",
    "Bono", "Yahia Fofana",
    "Mathew Ryan", "Andrew Redmayne",
    "Matt Turner", "Ethan Horvath",
    "Maxime Crépeau", "Milan Borjan",
    "Guillermo Ochoa", "Alfredo Talavera",
    "Keylor Navas", "Patrick Sequeira",
    "Ángel Mena", "Alexander Domínguez",
    "Sergio Rochet", "Sebastián Sosa",
    "Antony Silva", "Diego Melgarejo",
    "Pedro Gallese", "Carlos Cáceda",
    "Benji Siegrist", "Yann Sommer",
    "Lukáš Hrádecký", "Saša Kalajdžić",
    "Dominik Livaković", "Ivica Ivušić",
    "Jan Oblak", "Vanja Milinković-Savić",
    "Giorgi Mamardashvili",
    "Altay Bayındır", "Uğurcan Çakır",
    "Hiroki Sakai",
])

GRUPOS_DEFAULT = {
    "A": [("Mexico","Sudafrica"),("Corea del Sur","rep1"),("rep1","Sudafrica"),("Mexico","Corea del Sur"),("rep1","Mexico"),("Sudafrica","Corea del Sur")],
    "B": [("Canada","rep2"),("Catar","Suiza"),("Suiza","rep2"),("Canada","Catar"),("Suiza","Canada"),("rep2","Catar")],
    "C": [("Brasil","Marruecos"),("Haiti","Escocia"),("Escocia","Marruecos"),("Brasil","Haiti"),("Escocia","Brasil"),("Marruecos","Haiti")],
    "D": [("EEUU","Paraguay"),("Australia","rep3"),("rep3","Paraguay"),("EEUU","Australia"),("rep3","EEUU"),("Paraguay","Australia")],
    "E": [("Alemania","Curazao"),("Costa de Marfil","Ecuador"),("Alemania","Costa de Marfil"),("Ecuador","Curazao"),("Ecuador","Alemania"),("Curazao","Costa de Marfil")],
    "F": [("Paises Bajos","Japon"),("rep4","Tunez"),("Tunez","Japon"),("Paises Bajos","rep4"),("Japon","rep4"),("Tunez","Paises Bajos")],
    "G": [("Belgica","Egipto"),("Iran","Nueva Zelanda"),("Belgica","Iran"),("Nueva Zelanda","Egipto"),("Egipto","Iran"),("Nueva Zelanda","Belgica")],
    "H": [("España","Cabo Verde"),("Arabia Saudita","Uruguay"),("España","Arabia Saudita"),("Uruguay","Cabo Verde"),("Cabo Verde","Arabia Saudita"),("Uruguay","España")],
    "I": [("Francia","Senegal"),("rep5","Noruega"),("Francia","rep5"),("Noruega","Senegal"),("Noruega","Francia"),("Senegal","rep5")],
    "J": [("Austria","Jordania"),("Argentina","Argelia"),("Argentina","Austria"),("Jordania","Argelia"),("Argelia","Austria"),("Jordania","Argentina")],
    "K": [("Portugal","rep6"),("Uzbekistan","Colombia"),("Portugal","Uzbekistan"),("Colombia","rep6"),("Colombia","Portugal"),("rep6","Uzbekistan")],
    "L": [("Inglaterra","Croacia"),("Ghana","Panama"),("Inglaterra","Ghana"),("Panama","Croacia"),("Panama","Inglaterra"),("Croacia","Ghana")],
}


def bandera(nombre):
    return BANDERAS.get(nombre, "")
